name: Test Deployment

on:
  workflow_dispatch:

jobs:
  deploy-to-test:
    name: Deploy to Test Environment
    uses: benwk/github-action/.github/workflows/deployment-cloudflare-pages.yml@main
    with:
      environment: test
      public-domain: astro.benwk.app
      public-twitter: ${{ vars.PUBLIC_TWITTER }}
      ga-measurement: G-XXXXXXXXXX
      sentry-project-id: ${{ vars.SENTRY_PROJECT_ID }}
      sentry-org-id: ${{ vars.SENTRY_ORG_ID }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
