name: Test Deployment with E2E

on:
  pull_request_review:
    types: [submitted]

jobs:
  # deploy-to-test:
  #   name: Deploy to Test Environment
  #   uses: benwk/github-action/.github/workflows/deployment-cloudflare-pages.yml@main
  #   if: github.event.review.state == 'approved' && !contains(github.event.pull_request.head.ref, 'release')
  #   with:
  #     environment: test
  #     hostname: astro.benwk.app
  #     twitter: ${{ vars.TWITTER }}
  #     ga-measurement: G-xxxxxxx
  #     sentry-project-id: ${{ vars.SENTRY_PROJECT_ID }}
  #     sentry-org-id: ${{ vars.SENTRY_ORG_ID }}
  #     pr-id: ${{ github.event.pull_request.number }}
  #   secrets:
  #     SENTRY_PUBLIC_KEY: ${{ secrets.SENTRY_PUBLIC_KEY }}
  #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  component-e2e-tests:
    name: Component and E2E Tests
    uses: benwk/github-action/.github/workflows/test-cypress.yml@main
    if: github.event.review.state == 'approved' && !contains(github.event.pull_request.head.ref, 'release')
    with:
      local: true
      test-url: http://localhost:4321
      pr-id: ${{ github.event.pull_request.number }}
    secrets: inherit
